---
abstract: 'Session management for Mojo'
author:
  - 'Viacheslav Tykhanovskyi <vti@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-Session
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Digest::SHA: 0
  MIME::Base64: 0
  Mojolicious: 2.49
  Storable: 0
  Test::More: 0
  perl: 5.008007
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/vti/mojox-session
version: 0.26
