--- #YAML:1.0
name:               MojoX-Session
version:            0.19
abstract:           Session management for Mojo
author:
    - Viacheslav Tykhanovskyi <vti@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::SHA1:  0
    MIME::Base64:  0
    Mojo:          0.999924
    Storable:      0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
