--- #YAML:1.0
name:                MojoX-Session
version:             0.01
abstract:            Session management for Mojo
license:             perl
author:              
    - Viacheslav Tikhanovskii <vti@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    MIME::Base64:                  0
    Mojo:                          0
    Storable:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
